### ISSUE TITLE
The following configuration fields are not understood: {'database'}

### ISSUE THREAD

**Issue by anilk9096** [matrix-org/sygnal#115] opened 2020-05-11 09:48 UTC
sygnal service running . but not able to listen port 5000 why ? 

ps -def | grep sygnal
root      4115  2195  1 09:46 pts/3    00:00:00 python3.8 -m sygnal.sygnal
root      4121  2293  0 09:47 pts/4    00:00:00 grep --color=auto sygnal

netstat -pltun
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1246/sshd       
tcp6       0      0 :::22                   :::*                    LISTEN      1246/sshd       
udp        0      0 0.0.0.0:68              0.0.0.0:*                           985/dhclient

**Comment by clokep** [comment] 2020-05-11 12:03
This looks like a duplicate of #109. I'm going to close this, but if this isn't a duplicate, please let us know!

**Closed by clokep** 2020-05-11 12:03 UTC
