### ISSUE TITLE
ios notification -fluffyChat

### ISSUE THREAD

**Issue by Sphinix1** [matrix-org/sygnal#324] opened 2022-10-01 06:22 UTC
hi , 
i am using sygnal (self-hosted) with fluffychat. I dont seem to have notification pop-up unless fluffychat(ios) is running on the foreground.
i have tried all the suggestions i could find . what am i missing . 
here is my sygnal.yaml

```
apps:



    im.cvccc.cvcvc:
        keyfile: /data/AuthKey_zzzzzzzzz.p8
        team_id: xxcccccc
        key_id: cvvvvvvv
        topic: im.cvccc.cvcvc
        type: apns
                fcm_options:
                    content_available: true
                    priority: high
                    badge : 9
                    sound : bingbong.aiff
                    mutable_content: 1
http:
    bind_addresses:
    - '::'
    port: 6000
log:
    access:
        x_forwarded_for: true
    setup:
        disable_existing_loggers: false
        formatters:
            normal:
                format: '%(asctime)s [%(process)d] %(levelname)-5s %(name)s %(message)s'
        handlers:
            stderr:
                class: logging.StreamHandler
                formatter: normal
                stream: ext://sys.stderr
            stdout:
                class: logging.StreamHandler
                formatter: normal
                stream: ext://sys.stdout
        loggers:
            sygnal:
                handlers:
                - stderr
                propagate: false
            sygnal.access:
                handlers:
                - stdout
                level: INFO
                propagate: false
        root:
            handlers:
            - stderr
            level: INFO
        version: 1
metrics:
    opentracing:
        enabled: false
        implementation: jaeger
        jaeger:
            logging: true
            sampler:
                param: 1
                type: const
        service_name: sygnal
    prometheus:
        address: 0.0.0.0
        enabled: false
        port: 8000
    sentry:
        enabled: false
```

**Comment by DMRobertson** [comment] 2022-10-03 10:12
Duplicate of #323 and others.

**Closed by DMRobertson** 2022-10-03 10:12 UTC

**Comment by vanyasem** [comment] 2024-10-30 10:58
Also see #319 (https://github.com/famedly/matrix-dart-sdk/issues/1947, https://github.com/famedly/matrix-dart-sdk/issues/1948), #325, https://github.com/famedly/fcm_shared_isolate/issues/5 as these (separate) issues are also related to FluffyChat's push implementation

**Comment by vanyasem** [comment] 2024-10-30 11:02
FluffyChat does not seem to implement iOS foreground notifications (as it uses exclusively `fcm_shared_isolate` for it's FCM notifications, which lacks support for iOS altogether).

FluffyChat uses [krille-chan/fluffygate](https://github.com/krille-chan/fluffygate) as it's push gateway (https://push.fluffychat.im/), which sends `notification` pushes, which are handled by the OS itself on iOS (More on the difference between `notification` and `data` pushes [here](https://firebase.google.com/docs/cloud-messaging/concept-options)). Sygnal, on the other hand, only sends `data` pushes, which have to be processed by the app itself, which is not supported by FluffyChat.

See https://github.com/famedly/fcm_shared_isolate/issues/5 for an explanation and potential workarounds.
