### ISSUE TITLE
anyway to use gcm/fcm key as of today 24/10/2023 for android notification

### ISSUE THREAD

**Issue by hmanzer** [matrix-org/sygnal#353] opened 2023-10-24 14:39 UTC
We are trying to use gcm for android notification.
We have enabled `Cloud Messaging Legacy` and using the server key instead of api key but unable to get notification

```
 im.xxx.app:
    type: gcm
    api_key: <server key from legacy>
```

**Comment by rltas** [comment] 2023-11-01 11:31
#313

**Comment by clokep** [comment] 2023-11-02 12:36
I think this is a duplicate of #313, unfortunately there's no way to do this today as far as I know.

**Closed by clokep** 2023-11-02 12:36 UTC
